version = "0.1.3"
description = "Aviationstack MCP server."
readme = "README.md"

[project.scripts]
aviationstack-mcp = "aviatihgjhonstack_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
