[project]
name = "aviatiohgjhnstack-mcp"
version = "1.0.0"
description = "Aviationstack MCP server."
readme = "README.md"

[project.scripts]
aviationstack-mcp = "aviatihgjhonstack_mcp:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
